### ISSUE TITLE
При запуске Hiasm5 зависает (Ubuntu 14.04)

### ISSUE THREAD

**Issue by UUSR** [hiasmstudio/hiasm5#2]
Жалко не запускается ,сразу зависает и висит окно:
![_001](https://cloud.githubusercontent.com/assets/17599033/18225118/cee7f9fa-71eb-11e6-8f1e-3242b18054fd.png)
Пробовал запускать под root ,терминал выдаёт постоянно `Unknown property type: 0`и весит заставка постоянно.
![_002](https://cloud.githubusercontent.com/assets/17599033/18225134/3a9c5042-71ec-11e6-8e1e-dcf20b64e2f1.png)

**Comment by puux** [comment]
Базовый пакет установлен?

**Comment by UUSR** [comment]
@puux Да конечно ,собрал с помощью вашего скрипта и установил. Вот не пойму что такое Unknown property type: 0 ,и сильно процессор нагружается.

**Comment by puux** [comment]
Чтобы конструктор запустился нужно обязательно устанавливать пакеты hiasm5-common и hiasm5-pack-base

**Comment by UUSR** [comment]
@puux где взять hiasm5-pack-base?

**Comment by puux** [comment]
Добавлены скрипты для сборки hiasm5-base-pack

**Comment by UUSR** [comment]
@puux Оба пакета установлены в системе:
![_003](https://cloud.githubusercontent.com/assets/17599033/18256307/db0e84d2-73b3-11e6-9498-cee0bb4d47da.png)
Пробовал пересобрать сам hiasm5 из src с помощью make.
Ничего не получается опять после запуска hiasm5 висит окно и не запускается...
![_004](https://cloud.githubusercontent.com/assets/17599033/18256382/215c513e-73b5-11e6-9889-21a61c342efb.png)
Получилось три файла:
![_005](https://cloud.githubusercontent.com/assets/17599033/18256442/c813ae5a-73b5-11e6-9641-4631631eec4a.png)

**Comment by puux** [comment]
Эта ситуация возникает, когда отсутствует файл hiasm.db по адресу /usr/share/hiasm/int/. Данный файл ставится вместе с пакетом hiasm5-common. В списке установленных пакетом файлов это выглядит вот так:

![ScreenShot](http://i.mcgl.ru/iDSjQhzjTm)

**Comment by UUSR** [comment]
@puux Добрый вечер,
я посмотрел файлы на месте:
![screenshot_1](https://cloud.githubusercontent.com/assets/17599033/18367668/9ec62b04-761c-11e6-9cb5-68e8d23bd9f3.png)
Может надо сам файл hiasm5 положить в какую то специальную папку ?
Я его запускал с того места где скомпилировал.

**Comment by puux** [comment]
hiasm.db копируется в домашнюю директорию пользователя ~/.hiasm и используется от туда - может быть с этим проблема?
Местоположение hiasm5 не играет никакой роли.

**Comment by UUSR** [comment]
@puux Скопировал hiasm.db в ~/.hiasm ,запустилось вот такое окно:
![_006](https://cloud.githubusercontent.com/assets/17599033/18384512/338bb786-768b-11e6-96ed-e7f50c3927af.png)
Похоже в домашней директории ~/.hiasm чего то не хватает?

Всё вроде работает:
![_007](https://cloud.githubusercontent.com/assets/17599033/18384794/f5a86a34-768c-11e6-8c4c-41aeb6053cfd.png)

**Comment by puux** [comment]
А доступ к файлу  /usr/share/hiasm/int/hiasm.db с правами текущего пользователя есть? Других причин, по которым файл не удается скопировать быть не может.

**Comment by UUSR** [comment]
@puux уже скопировал и запустил ,нет компилятора ,создал новый Issues
